services:
  postgres:
    image: postgres:15
    container_name: gayam
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gayam
    volumes:
      - gayam-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  gayam-volume:
